# Generated by Django 2.2 on 2019-05-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='titile',
            new_name='title',
        ),
    ]
