# Generated by Django 2.2 on 2019-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=32)),
                ('gender', models.IntegerField()),
                ('level', models.IntegerField()),
                ('register_date', models.DateField()),
            ],
        ),
    ]
