# Generated by Django 2.2 on 2019-05-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.IntegerField(default=100),
        ),
    ]
