# Generated by Django 2.2 on 2019-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiorm', '0002_book_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
    ]
