# Generated by Django 2.2 on 2019-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='age',
            field=models.IntegerField(),
        ),
    ]
